--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp::DatabaseBackedModels
  ApplicationName: TestApp-DatabaseBackedModels
  Database: 
    CheckSchema: 1
    Database: testapp_databasebackedmodels
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::Record::Versioned
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: DEBUG
  Mailer: Sendmail
  MailerArgs: []

  Plugins: []

  PubSub: 
    Backend: Memcached
    Enable: ~
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
