---
framework:
  ActionBasePath: TestApp::Action
  AdminMode: 1
  ApplicationClass: TestApp
  ApplicationName: TestApp
  CurrentUserClass: TestApp::CurrentUser
  Database:
    Database: testapp
    Driver: SQLite
    Host: localhost
    Password: ''
    User: ''
    Version: 0.0.1
  Mailer: Sendmail
  MailerArgs: []
  Web:
    DefaultStaticRoot: /sw/lib/perl5/site_perl/5.8.6/darwin-thread-multi-2level/auto/Jifty/web/static
    DefaultTemplateRoot: /sw/lib/perl5/site_perl/5.8.6/darwin-thread-multi-2level/auto/Jifty/web/templates
    StaticRoot: web/static
    TemplateRoot: web/templates
